volumes:
  - name: "Jiefu Cerebellum FIB-SEM"
    path: "/groups/miaai/miaai/lmd-v0.0.1/jiefu-cerebellum-fibsem.zarr"
    image_key: "raw"
    zarr_version: "zarr2"
    scales: [0, 1, 2]
    label_key: "labels/agglom_seg"
    bounding_box: [[1197, 5561], [1457, 4773], [1132, 12109]]
    weight: 0.5
    normalize: true

  - name: "H01 Human Cortex"
    path: "/groups/miaai/miaai/lmd-v0.0.1/h01-human-cortex.zarr"
    image_key: "raw"
    zarr_version: "zarr3"
    scales: [0, 1, 2]
    weight: 0.5
    label_key: "labels/c3_seg"
    normalize: true

n_scales: 3
output_axes: "lcxyz"
patch_size: [64, 64, 16]
bbox_mode: "relative"
samples_per_epoch: 1000
cache_bytes: 1073741824
isotropic: true
