volumes:
  - name: "Jiefu Cerebellum FIB-SEM"
    path: "/groups/miaai/miaai/lmd-v0.0.1/jiefu-cerebellum-fibsem.zarr"
    image_key: "raw"
    axes: "zyx"
    zarr_version: "zarr2"
    scales: [0, 1, 2]
    label_key: "labels/agglom_seg"
    bounding_box: [[1197, 5561], [1457, 4773], [1132, 12109]]  # [z_min, z_max], [y_min, y_max], [x_min, x_max] (in voxels in storage axes order)
    weight: 0.5
    normalize: true  # Auto-normalize images to [0, 1] by dtype max (default: `true`)

  - name: "H01 Human Cortex"
    path: "/groups/miaai/miaai/lmd-v0.0.1/h01-human-cortex.zarr"
    image_key: "raw"
    axes: "xyz"
    zarr_version: "zarr3"
    scales: [0, 1, 2]
    weight: 0.5
    label_key: "labels/c3_seg"
    normalize: true  # Auto-normalize images to [0, 1] by dtype max (default: `true`)

output_axes: "xyz" # input will be automatically re-ordered to match this axes order (default: "xyz")
patch_size: [128, 128, 32]
samples_per_epoch: 1000
cache_bytes: 1073741824
