volumes:
  - name: "H01 Human Cortex"
    path: "/groups/miaai/miaai/lmd-v0.0.1/h01-human-cortex.zarr"
    image_key: "raw"
    zarr_version: "zarr3"
    scales: [0, 1, 2]
    weight: 1.0
    label_key: "labels/c3_seg"
    normalize: true

n_scales: 3
output_axes: "lcxyz"
patch_size: [128, 128, 32]
bbox_mode: "relative"
samples_per_epoch: 1000
cache_bytes: 1073741824
isotropic: true
